export const UserActionTypes ={
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER:'LOGIN_USER',
  LOGOUT_USER:'LOGOUT_USER',
  CHANGEPASSWORD_USER:'CHANGEPASSWORD_USER',
  CHANGEPHOTO_USER:'CHANGEPHOTO_USER',
  INTERESTGENDER_USER:'INTERESTGENDER_USER',
  INTERESTTYPE_USER:'INTERESTTYPE_USER',
  BLOCK_USER: "BLOCK_USER",
  RATE_USER:"RATE_USER"
};
export const ConversationActionTypes ={
  CREATE_CONVO :"CREATE_CONVO",
  UPDATE_CONVO :"UPDATE_CONVO",
  DELETE_CONVO :"DELETE_CONVO"
};
export const GenderActionTypes ={
  CREATE_GENDER :"CREATE_GENDER",
  UPDATE_GENDER :"UPDATE_GENDER",
  DELETE_GENDER :"DELETE_GENDER"
};